### ISSUE TITLE
pipenv 报错

### ISSUE THREAD

**Issue by RYLF** [greyli/helloflask#11]
环境：python2.7.13
错误描述：第一次安装pipenv成功，且创建了虚拟环境。第二次执行pipenv shell时候出现图片所示错误。
![](https://coding.net/u/RuoYun/p/testgit/git/raw/master/02.png)

**Comment by greyli** [comment]
@RYLF 请问这个项目文件夹包含哪些文件？

**Comment by RYLF** [comment]
![](https://coding.net/u/RuoYun/p/testgit/git/raw/master/03.png)

**Comment by greyli** [comment]
@RYLF 有没有手动修改Pipfile和Pipfile.lock？看看里面是否包含意外输入的中文字符。你的问题和[这个issue](https://github.com/pypa/pipenv/issues/2820)很像。因为我现在电脑不在身边，你可以先搜索一下看看能不能找到解决方案。

**Comment by greyli** [comment]
你好，请问问题解决了吗？上个评论提到的issue中创建者在重启电脑后问题消失了，你可以试一下。
