### ISSUE TITLE
疑似错误

### ISSUE THREAD

**Issue by xxiaocheng** [greyli/helloflask#113]
**注意：包括这行在内，下面斜体的为模板提示文字，可以删除掉。**

*反馈勘误前，请先查看一下[勘误文件](https://github.com/greyli/helloflask/blob/master/errata/errata.md)，看看是否已经记录。可以通过错误的页数或章节号尝试进行搜索。*

*提示：如果下面的格式没法满足你的需求，可以全部删除。*

* 章节位置（比如3.3.2）：2.5.4.1
* 页数（如果是纸书的话）：P67
* 错误文字：db.execute('SELECT * FROM students WHERE password=?,password)
* 正确文字：db.execute('SELECT * FROM students WHERE password=?',password)
* 备注：" ' "不完整

**Comment by greyli** [comment]
感谢反馈，勘误里已经包含这一处了。

**Comment by xxiaocheng** [comment]
说我没有留意下面的  不重要勘误 ,不好意思

**Comment by greyli** [comment]
嗯，没事的 :)
