### ISSUE TITLE
7.3.2　快捷渲染表单 中的示范代码有误

### ISSUE THREAD

**Issue by python012** [greyli/helloflask#12]
这一节中有一段示范代码

{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block content %}
    <div class="hello-form">
        **{{ render_form(form),action=request.full_path}}**
    </div>
{% endblock %}

对比github上源代码，其中应该是`{{ render_form(form, action=request.full_path) }}`

**Comment by greyli** [comment]
@python012 这个是后续跟编辑反映改动，编辑弄错了，不好意思。晚点会加到勘误里，感谢反馈！

**Comment by greyli** [comment]
已更新勘误。
