### ISSUE TITLE
4.4.5 使用Flask-CKEditor集成富文本编辑器  2. 渲染富文本编辑器 提示 文档链接打开为空

### ISSUE THREAD

**Issue by Ecvelnter** [greyli/helloflask#121]
你好，电子书（亚马逊）

4.4.5 使用Flask-CKEditor集成富文本编辑器 
2. 渲染富文本编辑器 
提示
“更多详情可访问Flask-CKEditor文档的配置部分（https://flask-ckeditor.readthedocs.io/configuration.html）”

这个链接打开显示页面未存在。

**Comment by greyli** [comment]
感谢反馈！这里写错了，实际地址是 [https://flask-ckeditor.readthedocs.io/en/latest/configuration.html](https://flask-ckeditor.readthedocs.io/en/latest/configuration.html)。

**Comment by Ecvelnter** [comment]
好的。
刚已通过第四章开头的Python包介绍进入Flask-CKEditor文档查得。
这种在章节开头列出相应资源链接的方式挺好的：）

此外，电子书的勘误后续会有推送更新吗？

**Comment by greyli** [comment]
每次纸书重印都会更新电子书，最近的一次大概在下个月。

**Comment by Ecvelnter** [comment]
赞！
