### ISSUE TITLE
token验证部分求助

### ISSUE THREAD

**Issue by cainiao308** [greyli/helloflask#128]
@auth_bp.route('/confirm/<token>')    #验证token
@login_required
def confirm(token):
    print 111
    if current_user.confirmed:
        return redirect(url_for('main.index'))

    if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
        flash('Account confirmed.', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('.resend_confirm_email'))

这段代码中，发送了confirm邮件之后，需要验证邮箱，为什么要加@login_required呢？
加了点击邮箱确认连接会跳转到登录页面

**Comment by greyli** [comment]
需要验证当前登录用户和被确认的用户一致。

**Comment by greyli** [comment]
先关闭了，有问题可以继续评论或重开。
