### ISSUE TITLE
p239勘误

### ISSUE THREAD

**Issue by brakchen** [greyli/helloflask#134]
* 章节位置（比如3.3.2）：
* 页数（如果是纸书的话）：p239
* 错误文字：代码清单8-12 bluelog/commands.py: 生成博客虚拟数据
* 正确文字：代码清单8-12 bluelog/_\_init__.py: 生成博客虚拟数据
* 备注：查看过github的内容，并没有 bluelog/commands.py这个文件，所有的command都是注册在_\_init__.py内

**Comment by greyli** [comment]
这里的确是笔误，已经更新到勘误中了，谢谢！
