### ISSUE TITLE
关于flask forge 命令报错

### ISSUE THREAD

**Issue by brakchen** [greyli/helloflask#135]
我不知道这个内容算是勘误还是内容排版问题
在书中p240也中运行生成fake 数据的命令后```flask forge``` 会出现错误```AttributeError: 'Admin' object has no attribute 'set_password'```
在 p234 代码清单8-5 建立数据库模型的时候讲到了```Admin```模型的建立，文中提示部分提了关于```password_hash```的问题，说了会以后讲。这个password部分的内容确实在很后面讲了，既然需要用到相关内容，我觉得应该把模型部分的代码补全在书上，这样才不会导致运行```flask forge```命令的时候出现错误。
同时在p236 代码清单中倒数第三行出现了```admin.set_password('helloflask')``` 如果没有后面关于```password_hash``` 的内容会对这个函数的出现感到莫名其妙

github 代码：
```python
class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20))
    password_hash = db.Column(db.String(128))
    blog_title = db.Column(db.String(60))
    blog_sub_title = db.Column(db.String(100))
    name = db.Column(db.String(30))
    about = db.Column(db.Text)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password_hash, password)
```
书中代码：
```python
class Admin(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20))
    password_hash = db.Column(db.String(128))
    blog_title = db.Column(db.String(60))
    blog_sub_title = db.Column(db.String(100))
    name = db.Column(db.String(30))
    about = db.Column(db.Text)
```

**Comment by greyli** [comment]
你好，感谢反馈！237 页的那一行 `admin.set_password('helloflask')` 调用应该删除，在那个阶段对应的代码（使用 `git checkout skelton` 命令签出）里没有这一行（[源码](https://github.com/greyli/bluelog/blob/skeleton/bluelog/fakes.py#L19-L28)）。275 页应该添加一个提示来提及添加这一行调用。

**Comment by greyli** [comment]
先关闭了，我稍后会更新到勘误里。
