### ISSUE TITLE
p246代码片段错误

### ISSUE THREAD

**Issue by brakchen** [greyli/helloflask#136]
* 章节位置（比如3.3.2）：
* 页数（如果是纸书的话）：p246
* 错误文字：```flask(u'发表成功！', 'success')```
* 正确文字：```flask('success', u'发表成功！')```
* 备注：根据p245中间段的内容如果with_categories=True的话会返回一个(分类，消息)的元组，根据模板上面代码来看返回一个(分类，消息)的元组是正确的，所以在p246中的代码片段是有误的

**Comment by greyli** [comment]
你好，`flash()` 接受的参数位置和返回的元组内元素的顺序不相同。具体可参考[源码](https://github.com/pallets/flask/blob/master/flask/helpers.py#L386)：
```py
def flash(message, category='message'):
    ...
    flashes.append((category, message))
    ...
```
