### ISSUE TITLE
P164 5.5.3 多对一  里的疑问

### ISSUE THREAD

**Issue by Merpyzf** [greyli/helloflask#141]
原文:

> 在定义关系时，外键总是在“多”这一侧定义，所以在多对一关系中外键和关系属性都是定义在“多” 这一侧，即City类中。

对上文存在疑问，根据给出的代码来看 外键和关系属性 全都定义在了Citizen类中而不是上文描述的City类中。所以上文的”City类“是否存在笔误？

**Comment by greyli** [comment]
你好，感谢反馈。这里是笔误，已在[勘误](http://helloflask.com/book/errata/1-1/)里标出。
