### ISSUE TITLE
Bootstrap-Flask快捷渲染表单更新

### ISSUE THREAD

**Issue by woxihejinghao** [greyli/helloflask#149]
Bootstrap-Flask快捷渲染表单的方法已经更新了
旧版：
{% from 'bootstrap/form.html' import render_form %}
新版：
{% from 'bootstrap/wtf.html' import quick_form %}

顺便请问我使用的是电子版，是否会进行更新

**Comment by greyli** [comment]
你给出的第二种渲染方法是 Flask-Bootstrap 扩展，和 Bootstrap-Flask 是两个不同的扩展。

哪个平台的电子版？

**Comment by woxihejinghao** [comment]
哦，我使用的是豆瓣的

**Comment by woxihejinghao** [comment]
哈哈，新手不清楚这两个扩展

**Comment by greyli** [comment]
好的。豆瓣第 2 次印刷版本前段时间已经联系客服赠送过了。
