### ISSUE TITLE
豆瓣阅读电子书第八章两处错误

### ISSUE THREAD

**Issue by pyclear** [greyli/helloflask#158]
model 评论的第二段示例代码`backref="Post" `是错误的
应为`comments = db.relationship("Comment", back_populates="post", cascade="all")`

**Comment by pyclear** [comment]
另外，豆瓣电子书，已close掉的第八章 set_password那个代码执行结果cat 是Flase的issue，还是False

**Comment by greyli** [comment]
感谢反馈，这两处已经在到勘误中了。请问你的电子书是新版本吗？第二次更新的版本应该已经修复了这些问题。上次我和豆瓣客服交涉之后，他们回复将会给购买旧版本的读者赠送新版本，没有收到吗？

**Comment by pyclear** [comment]
我直接web端看的，理论上应该是最新。

**Comment by greyli** [comment]
和在哪里看没关系，你需要确认豆瓣消息提醒里有没有赠送通知，另外再打开[这个页面](https://read.douban.com/ebook/106866366/)查看是否能够进行阅读和评论等操作。

**Comment by pyclear** [comment]
没有， 可能是豆瓣有bug，一边我可以读，一边又要我付费

**Comment by greyli** [comment]
好的，那[这个链接](https://read.douban.com/ebook/106866366/)打开后能点击阅读和评论等按钮吗？（豆瓣每次更新后会删掉原来的那个商品，创建一个新的。如果你购买的是旧商品，在新的商品页面会显示未购买当前商品）

**Comment by pyclear** [comment]
能点击，但是需要购买。

**Comment by greyli** [comment]
那请把你的豆瓣阅读个人主页 URL 发给我，我问问客服（可以通过邮件私发给我）。

**Comment by pyclear** [comment]
https://read.douban.com/people/pyclear/

**Comment by greyli** [comment]
已联系豆瓣客服，正在等待回复。另外，麻烦再确认一下你的礼物记录：

![image](https://user-images.githubusercontent.com/12967000/54093901-99455c00-43d7-11e9-9d55-44d65bb9af3d.png)

**Comment by greyli** [comment]
豆瓣客服的回复如下：
> 您好，已赠送，请到「我的」-「我购买的电子书」中查看。

**Comment by pyclear** [comment]
是的已经收到了，这个体验挺糟糕的，app端之前好像看书是会自己处理的。我还觉得挺好用的，现在得给差评了。

**Comment by greyli** [comment]
国内的几个电子书平台都挺糟糕的，不论是阅读客户端，排版还是产品逻辑。个人觉得，技术书只有包含代码语法高亮的 PDF 才有可读性，不过出于各种原因，大部分出版社都不提供。
