### ISSUE TITLE
第五章166页，代码清单db.Table类的第一个参数问题

### ISSUE THREAD

**Issue by yeshan333** [greyli/helloflask#164]
代码清单中db.Table类传入的第一个参数（association）并非关联表的名称（association_table），与下面说明不符

**Comment by greyli** [comment]
association 是「关联表的名称」，而 association_table 是「关联表对象的名称」。

**Comment by yeshan333** [comment]
> association 是「关联表的名称」，而 association_table 是「关联表对象的名称」。

那后面关系函数的secondary参数又说要关联表的名称。。。。。。。

**Comment by greyli** [comment]
不好意思，后面这里是我写错了。不过 secondary 参数传入关联表的名称（字符串形式）或关联表对象的名称都可以。稍后会把这一条加进勘误。

**Comment by greyli** [comment]
已更新到勘误，感谢反馈。
