### ISSUE TITLE
2.2.3.1 P34 表2-5 

### ISSUE THREAD

**Issue by hp66722667** [greyli/helloflask#166]
位置：P34 2.2.3.1：路由匹配 第五行   你可以尝试在预览器中访问http://localhost:5000/nothing,

图片2-5 404错误响应的 截图网址是127.0.0.1:5000/foo

段落描述与截图的链接网址不同

**Comment by greyli** [comment]
感谢反馈，这一处勘误里已经有了，而且已经在第二次印刷中修正。
