### ISSUE TITLE
P189 疑似代码错误

### ISSUE THREAD

**Issue by xxiaocheng** [greyli/helloflask#168]
你好,P189 6.3.2 使用Jinja2 模版组织邮件正文  上方的部分代码 
`mail=Mail(from_email,subject,to_email,content=[text_content,html_content])`
其中参数 `content` 传入列表类型会错误,看了下 源码,content 不应该为列表类型,不知我是否有疏漏,望确认 .

**Comment by greyli** [comment]
你好，感谢反馈。请使用 5.3.0 版本的 sendgrid，详情见 https://discuss.helloflask.com/t/topic/135

**Comment by xxiaocheng** [comment]
> 你好，感谢反馈。请使用 5.3.0 版本的 sendgrid，详情见 https://discuss.helloflask.com/t/topic/135

不好意思 ,未注意到讨论区更正

**Comment by greyli** [comment]
没关系 :)
