### ISSUE TITLE
vs2017无法运行并且控制台没有报错

### ISSUE THREAD

**Issue by JOHNykn** [greyli/helloflask#170]
把源码复制到vs2017自己的项目文件后运行无反应，控制台输出如下：
![image](https://user-images.githubusercontent.com/40849489/56102245-6e15d580-5f5e-11e9-91cc-853cd9ea9587.png)
虚拟环境如下：
![image](https://user-images.githubusercontent.com/40849489/56102275-9bfb1a00-5f5e-11e9-8d83-93c77c9200c6.png)
项目目录结构如下：
![image](https://user-images.githubusercontent.com/40849489/56102290-b9c87f00-5f5e-11e9-80eb-d7ceeee4612f.png)

**Comment by greyli** [comment]
哪个项目？使用什么方式 / 命令运行的？

**Comment by JOHNykn** [comment]
空白flask web项目，直接点击上面的运行按钮运行的。自己写的代码能正常运行。

**Comment by greyli** [comment]
@JOHNykn Flask 项目使用 IDE 的运行按钮启动需要进行一些配置。我没用过 VS 开发 Flask，具体方法你找找看。

**Comment by JOHNykn** [comment]
已解决，在要运行的文件内粘贴如下代码:
if __name__ == '__main__':
    import os
    HOST = os.environ.get('SERVER_HOST', 'localhost')
    try:
        PORT = int(os.environ.get('SERVER_PORT', '5555'))
    except ValueError:
        PORT = 5555
    app.run(HOST, PORT)
目前还不清楚原因
