### ISSUE TITLE
多看书城电子版不更新文件版本

### ISSUE THREAD

**Issue by microlee** [greyli/helloflask#173]

**Comment by microlee** [comment]
多看书城本书的电子版目前还是20180901第一版的原始状态，可否请版权方作者提醒多看进行勘误更新啊，我等买了正版电子书的用户因大量勘误未修正，严重影响阅读体验，请作者帮助，十分感谢！

**Comment by microlee** [comment]
![Uploading image

.png…]()

**Comment by greyli** [comment]
联系客服了吗？麻烦提供和客服的聊天记录，我和出版社沟通下。

**Comment by greyli** [comment]
多看回复今天完成了更新，请确认。

**Comment by greyli** [comment]
已收到其他读者的确认，关闭了。

**Comment by Sefank** [comment]
多看还是不更新呀，从20190527之后就再也没更新了，麻烦作者再多提醒一下多看进行勘误更新啊，电子版不像纸质版，图片上是没有办法批注修改的，内容不改就很难受……十分感谢！

**Comment by greyli** [comment]
电子书平台对更新文件这件事大都不是很合作……我明天试试跟出版社反馈下。

**Comment by Sefank** [comment]
> 电子书平台对更新文件这件事大都不是很合作……我明天试试跟出版社反馈下。

了解，非常感谢帮忙联系，多看客服已经基本失能;)

**Comment by greyli** [comment]
@Sefank 出版社回复亚马逊和腾讯今天已经更新，其他平台大概 2~3 天内会更新，到时可以留意一下。不过还有一个问题是电子书平台默认不主动推送更新，你可能到时还得联系客服帮你更新文件……

**Comment by Sefank** [comment]
@greyli 多看这边回复说出版社给的文件没有更新TAT

**Comment by greyli** [comment]
@Sefank 好，我再跟进下

**Comment by Sefank** [comment]
@greyli 弱弱问一下有结果了嘛？

**Comment by greyli** [comment]
@Sefank 刚问了，出版社回复文件 23 号给了多看对接人，刚刚又去确认了下，多看已经更新了。

**Comment by Sefank** [comment]
> @Sefank 刚问了，出版社回复文件 23 号给了多看对接人，刚刚又去确认了下，多看已经更新了。

好的我重新下载了文件看到更新了，非常感谢大佬的跟进！

**Comment by greyli** [comment]
不客气 :)

**Comment by greyli** [comment]
@Sefank 你好，请问方便把更新后的文件前言第一段发给我看一下吗（截图就可以）？我想确认下更新的版本。

**Comment by Sefank** [comment]
@greyli 
![前言截图](https://user-images.githubusercontent.com/12670778/103476251-0a48d580-4def-11eb-8265-b019014962ec.png)

**Comment by greyli** [comment]
@Sefank 好的，谢谢！
