### ISSUE TITLE
 代码勘误: 第二版，第4章, p120, 最下面代码段，倒数第3，4行

### ISSUE THREAD

**Issue by slooring** [greyli/helloflask#183]
{{ form_field(form.username) }}<br>
{{ form_field(form.password) }}<br>

macros.html里已经有<br>了，这里是否应该没有<br>?

{{ form_field(form.username) }}
{{ form_field(form.password) }}

**Comment by greyli** [comment]
没太理解你的意思。macros.html 里定义了这个 form_field 宏的具体定义（做哪些事情），下面这两行是在实际调用这个宏。

**Comment by greyli** [comment]
先关闭了，后续有问题可以继续评论或重开。
