### ISSUE TITLE
安装Pipenv的时候搞不定

### ISSUE THREAD

**Issue by blindkey** [greyli/helloflask#19]
感觉是本地有virtualenv和 pyenv 的关系
每次使用pipenv的时候如下所示:
![image](https://user-images.githubusercontent.com/703783/45597404-6ad55e00-b9fe-11e8-8f6f-2bb7d3c89d44.png)
跟书上不同

**Comment by greyli** [comment]
看图片并没有报错，是出现什么问题了吗？

**Comment by MiracleWong** [comment]
感觉你这是已经安装好了`Pipenv `后，开启了`sqldb`环境，但是`pipenv install` 为空导致的。你试一下`pip install flask`，应该是可以的。我的情况和你的类似。

**Comment by hectoraaphrodite** [comment]
我第一次安装pipenv时，情况跟他一样，好像没关系，可以正常使用呀

**Comment by greyli** [comment]
@blindkey 刚刚发现，你似乎已经激活了某个虚拟环境（`sqldb`）？
