### ISSUE TITLE
微信站长认证怎么解决

### ISSUE THREAD

**Issue by 99Kies** [greyli/helloflask#197]
作者有接触过微信打开页面，但是需要进行站长认证吗

这个文件应该咋放呢？？？

![qq_pic_merged_1576165020554](https://user-images.githubusercontent.com/45918704/70726114-88e05a00-1d38-11ea-8deb-cf27db8ac266.jpg)

该如何部署啊？  
我是这样子写的
```python
@app.route('/tencentxxxxx.txt')
def tencent():
    return 'msg balabala'
```

**Comment by greyli** [comment]
你这样写不起作用吗？

不起作用的话可以试试创建一个实际的 txt 文件放到 static 文件夹，然后这样写：

```py
from flask import send_from_directory

@app.route('/tencentxxxxx.txt')
def tencent():
    return send_from_directory(app.static_folder, 'tencentxxxxx.txt')
```
