### ISSUE TITLE
第4章当中，设置了表单校验，不满足情况时报错不会变红

### ISSUE THREAD

**Issue by moutsea** [greyli/helloflask#199]
如题：

![image](https://user-images.githubusercontent.com/22448894/74741861-8ea66e80-5298-11ea-8cb7-5f02d022a215.png)

此处应该为红色，css已经成功加载，百思不得其解，求大神解惑

**Comment by greyli** [comment]
可能是浏览器缓存了旧的 CSS 文件，试试清理缓存或是给 CSS 文件换个名字。

**Comment by moutsea** [comment]
感谢回复。两种方法都试过了，还是不行，有点奇怪。这个问题在Chrome下会发生，换成Safari就好了。我查了Chrome加载的css，就没有出现red这一项。猜测是不是因为是先加载的css再动态生成的标签，所以导致了这个问题？

![image](https://user-images.githubusercontent.com/22448894/74821171-27db9080-533e-11ea-8f8f-5293e9b787ce.png)

**Comment by greyli** [comment]
发一下相关代码吧，表单的渲染代码和 CSS  定义。

**Comment by moutsea** [comment]
我就是照着您的代码写的，我试了下您的代码，也是一样的。。。

**Comment by greyli** [comment]
推测还是你的 CSS 文件有问题，我在本地试了下正常（用这个仓库代码的话，记得清除浏览器缓存）：

![image](https://user-images.githubusercontent.com/12967000/74929333-3bf2c100-5416-11ea-891c-150cc6705a3c.png)

**Comment by greyli** [comment]
或者你用浏览器的元素选择器指向错误消息，然后再看下对应的 CSS 定义。

**Comment by greyli** [comment]
先关闭了，问题没解决的话可以重开。
