### ISSUE TITLE
 第七章留言板无法运行，显示import error

### ISSUE THREAD

**Issue by blindkey** [greyli/helloflask#20]
关于第七章中的目录结构和 python的包含机制
我没有看特别懂，自己按照这个目录照抄的时候，也发现并不能运行，死在

import views 这里就报错了.
已经
export FLASK_APP=demo
flask run了

**Comment by greyli** [comment]
方便提供一下相关代码和错误信息吗？

**Comment by greyli** [comment]
长时间未回复，先关闭了，后续有问题可以再打开。
