### ISSUE TITLE
在python-dotenv那里卡了很久

### ISSUE THREAD

**Issue by chuixing** [greyli/helloflask#200]
李老师好。

我按着这本书练习的时候，在python-dotenv那里卡了很久。只要python-dotenv一装上，demos下的app.py就404 。今天才明白过来，把根目录下的.env .flaskenv删除，项目就可以访问了。

**Comment by greyli** [comment]
嗯……我当初也卡在这里很久。我记得上次想去修这个 bug，但是又复现不了。好像新版本 Flask 和 Werkzeug 已经解决了这个问题？有时间可以更新版本试试。

**Comment by greyli** [comment]
在 Flask 创建了一个对应的 issue（<https://github.com/pallets/flask/issues/3561>），这个先关闭了。总之，避免出现这个问题的方法就是不要在程序模块（app.py）或包的顶层创建 .env 或 .flaskenv 文件。
