### ISSUE TITLE
sendgrid 

### ISSUE THREAD

**Issue by l1725821492** [greyli/helloflask#201]
sendgrid 现在注册需要填写很多信息而且注册了无法登录，还有没有其他的邮件服务商。

**Comment by greyli** [comment]
[替代品很多](https://www.google.com/search?q=sendgrid+alternatives&oq=sendgrid+alternatives&aqs=chrome.0.0l8.8440j0j7&sourceid=chrome&ie=UTF-8)，如果想用国内的服务，可以试试腾讯企业邮箱。
