### ISSUE TITLE
本地加载bootstrap.min.js

### ISSUE THREAD

**Issue by liveforday** [greyli/helloflask#203]
```
<small data-toggle="tooltip" data-placement="top" 
data-timestamp="{{ message.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}" 
data-delay="500">
                {{ moment(message.timestamp).fromNow(refresh=True) }}
</small>
```
本地加载bootstrap.min.css  上述代码无法正常工作。
时间正常显示，但是显示位置不正确，tooltip功能也没有实现，鼠标悬浮在时间元素上，没有悬浮提示框出现。在不改动任何其他代码的情况下，通过CDN网络加载bootstrap.min.js文件，页面渲染正常，而且tooltip悬浮窗口正常。请问是什么原因啊？

**Comment by liveforday** [comment]
我在base.html文件中 使用
·``{{ bootstrap.load_css() }}`` 替换了``<link src="{{url_for('static', filename='css/bootstrap.min.js')}}">``解决了这个问题，但是我不明白为什么。我确保我使用的是bootstrap-flask，而不是flask-bootstrap。

**Comment by greyli** [comment]
tooltip 功能依赖 Popper.js（Bootstrap 以外的第三方依赖），所以除了 bootstrap.min.js 外还要加载 Popper 的 JavaScript 文件。

你前面描述里有很多地方比较混乱，我按照我的理解忽略了：

> 本地加载**bootstrap.min.css** 上述代码无法正常工作

你指的是 bootstrap.min.js？

> 我在base.html文件中 使用 **{{ bootstrap.load_css() }}** 替换了

bootstrap.load_css() 是用来加载 CSS 文件的，你指的是 bootstrap.load_js()？

> `'css/bootstrap.min.js'`

按理说，JavaScript 文件会存储在 js 子文件夹内

**Comment by liveforday** [comment]
谢谢你的回复，是我描述的有问题，笔误太多了-_-||
1. 标题我想说的是本地加载``bootstrap.min.css``
2. ``bootstrap.load_css() `` 替换了``<link href="{{url_for('static', filename='css/bootstrap.min.css')}}">``
***
但是，看到你的回复后我又做了很多尝试。发现并不是``bootstrap.load_css()``帮我解决了问题。而是我有两个工程，sayhello和bluelog。sayhello的tooltip功能正常。为了对比找出问题，我会在两个工程之间切换运行。bluelog的tooltip功能恢复正常，实际上是浏览器缓存使用了sayhello的css资源造成的假象，而不是``bootstrap.load_css()``起作用了！！！。
当我ctrl+F5强制浏览器重载资源，bluelog的tooltip功能果然又失效了。所以我认为是bluelog目录下的css文件有问题，而不是加载过程出了问题，于是我用sayhello工程中的css文件，覆盖了bluelog的css文件。nice!!!!。无论我怎么切换工程，强制浏览器重载css资源，还是使用任何一种方式加载本地css文件，都能让tooltip功能正常运行了。

**Comment by greyli** [comment]
哈哈，解决了就好。
