### ISSUE TITLE
第一章：动态URL中的例子发现有BUG

### ISSUE THREAD

**Issue by zzmacoolboy** [greyli/helloflask#204]
```
@hello.route('/greet', defaults={'name': '程序员'})
```
这样写是有区别的，访问http://127.0.0.1:5000/greet/ 或 http://127.0.0.1:5000/greet时
报错：The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
必须写成 @hello.route('/greet/', defaults={'name': '程序员'})  
```
# @hello.route('/greet/', defaults={'name': '程序员'})
@hello.route('/greet/')
@hello.route('/greet/<name>')
def func_greet(name='程序员'):
    print('调用func_greet ()函数')
    return '<h1>Hello - 你好啊，欢迎您 %s</h1>' %(name)
```

**Comment by greyli** [comment]
在 Flask 里，`'/greet'` 和 `'/greet/'` 是两个不同的 URL 规则，具体的行为可以参考[文档](https://flask.palletsprojects.com/en/1.1.x/quickstart/#unique-urls-redirection-behavior)。

**Comment by greyli** [comment]
先关闭了，问题没解决可以重开。
