### ISSUE TITLE
第二章自定义全局函数和自定义测试器

### ISSUE THREAD

**Issue by lxq1** [greyli/helloflask#205]
使用@自定义全局函数和自定义测试器 装饰器会报错
@app.template_global()
@app.template_test()

用app.jinja_env.globals['bar'] = bar

app.jinja_env.tests["baz"] = baz

正常运行

**Comment by greyli** [comment]
请贴一下完整的全局函数和自定义测试器代码，以及完整的报错。

**Comment by greyli** [comment]
缺乏足够的信息，先关闭了，如果没解决欢迎重开或继续评论。
