### ISSUE TITLE
生成虚拟数据命令无法注册进app

### ISSUE THREAD

**Issue by yqf0201** [greyli/helloflask#207]
您好  @greyli，我的项目是一个社交博客，再bluelog中的forge（）函数的基础上，稍作改动写了setup（）但是当我运行时，报错找不到这个命令。
代码如下：
```py
import click
def register_commands(app):
    @app.cli.command()
    @click.option('--user', default=100, help='Quantity of users,  default is 100.')
    @click.option('--post', default=200, help='Quantity of posts, default is 200.')
    @click.option('--comment', default=300, help='Quantity of comments, default is 300.')
    def setup(user, post, comment):
        """Generate fake data."""
        from app.fake import users, posts, comments

        db.drop_all()
        db.create_all()

        click.echo('Inserting roles...')

        from app.models import Role
        Role.insert_roles()

        click.echo('Generating the users...' % user)
        users(user)

        click.echo('Generating %d posts...' % post)
        posts(post)

        click.echo('Generating %d comments...' % comment)
        comments(comment)

        click.echo('Done.')
```
报错如下：
```
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'setup'.
```

**Comment by greyli** [comment]
执行 `flask --help` 命令会输出什么？

**Comment by yqf0201** [comment]
以下是结果：
Usage: flask [OPTIONS] COMMAND [ARGS]...

  This shell command acts as general utility script for Flask applications.

  It loads the application configured (through the FLASK_APP environment
  variable) and then provides commands either provided by the application or
  Flask itself.

  The most useful commands are the "run" and "shell" command.

  Example usage:

    set FLASK_APP=hello.py
    set FLASK_DEBUG=1
    flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

**Comment by greyli** [comment]
没有报错我也很难判断出问题原因，你可以逐个删减命令函数里的函数调用，看看能不能用排除法找到出问题的代码。

另外你的程序用 flask run 可以正常运行吗？

**Comment by yqf0201** [comment]
flask run 可以正常运行。好的，我试试逐个删减的方法，谢谢！

**Comment by greyli** [comment]
先关闭了，如果没有解决可以重新打开或评论。或者你可以把项目源码上传到 GitHub，然后把链接发给我，我手动运行一下会更容易找到问题原因。
