### ISSUE TITLE
第1版第6次印刷P237代码清单8-9导入语句拼写错误

### ISSUE THREAD

**Issue by l346490199** [greyli/helloflask#210]
第一行
`from sqlal chemy.exc import IntegerityError`

- 【sqlal chemy.exc】   中间多了空格
- 【ImtegerityError】  中间多了一个e

我被这个e折磨了半天  一直报错  怀疑自己插件装错了

**Comment by greyli** [comment]
感谢反馈，稍后会加到勘误里，抱歉给你带来困扰……

**Comment by greyli** [comment]
已更新到 [1-6 勘误](https://github.com/greyli/helloflask/blob/master/errata/errata1-6.md)，谢谢。
