### ISSUE TITLE
第4章 4.3.2 P115 勘误

### ISSUE THREAD

**Issue by Yuxiaoy1** [greyli/helloflask#212]
4.3.2 验证表单数据
-----2. WTForms 验证机制
代码块部分勘误：
根据代码块验证结果，`password`字段的长度验证器应为`Length(6)`，书中为`Length(8,128)`，与后续验证结果不一致

**Comment by greyli** [comment]
感谢反馈！你的意思是不是指错误消息和验证器设置不匹配？如果是的话，在新版本里这一处已经更正了（错误消息改为了 `Field must be at least 8 characters long.`）。

**Comment by Yuxiaoy1** [comment]
是这个问题，根据`form1`和`form2`的验证结果（`form2`的`password`字段长度6位通过验证），猜测用的验证器为`Length(6)`
目前我看到的版本中此处验证器为`Length(8,128)`，如果验证器没有错误，未通过该验证的内置错误消息应为`Field must be between 8 and 128 characters long.` (`Flask-WTF`版本为0.14.3)

**Comment by greyli** [comment]
上次把 form2 的输入密码长度也改成了 8，下次再把 `Length(8, 128)` 改为 `Length(8)` 就可以保持一致了。

**Comment by Yuxiaoy1** [comment]
P106，P108代码块中`Length(8,128)`应保持一致，另建议定义`min`, `max`两个参数，让读者多了解该验证器中参数的含义及使用。

**Comment by greyli** [comment]
谢谢，那我还是改一下错误消息比较简单。参数的话在表 4-3 有注明，我再考虑下。

**Comment by greyli** [comment]
已更新到勘误文件（更新了错误消息），谢谢。
