### ISSUE TITLE
第4章 4.4.4 文件上传 勘误

### ISSUE THREAD

**Issue by Yuxiaoy1** [greyli/helloflask#213]
1. P126 (2) 使用过滤后的文件名中的代码，`from werkzeug import secure_filename` 应为 `from werkzeug.utils import secure_filename`
2. P128 代码清单 4-16 中，「验证 `CSRF` 令牌」及「检查文件是否存在」代码，在`POST`方法提交`MultiUploadForm`表单时，使用`if form.validate_on_submit()`写法，`Flask-WTF`会自动对`csrf_token`及`photo`字段进行验证（`photo`字段使用了`DataRequired`验证器），因此这部分手动验证的代码是否可以优化？

**Comment by greyli** [comment]
多文件验证目前还不支持，所以需要手动验证。我提交了一个 [PR](https://github.com/lepture/flask-wtf/pull/338) 但是没有被合并。
