### ISSUE TITLE
第5章 数据库 勘误

### ISSUE THREAD

**Issue by Yuxiaoy1** [greyli/helloflask#214]
1. P150处勘误：根据上下文，第二个Python Shell中的代码应为`print(Note.query.filter(Note.body=='SHAVE'))`，而非`...filter_by(body='SHAVE')...`，P151才引出filter_by()方法
2. P153处勘误：代码清单5-5中`form = DeleteForm()`应为`form = DeleteNoteForm()`
3. P160处勘误：第一个提示中「我们也可以直接将关系属性赋值给一个包含Article对象的列表。」意思表达反了，应为「我们也可以直接将关系属性赋值为一个包含Article对象的列表。」
4. P165处勘误：代码清单5-14中两个类的关系属性`capital`和`country`并未进行连接，须更新为`capital = db.relationship('Capital', back_populates='country', uselist=False)`和`country = db.relationship('Country', back_populates='capital')`
5. P177处勘误：「然后在函数中可以使用参数名作为键来从**kwargs字典获取对应的参数值」应为「然后在函数中可以使用参数名作为键来从kwargs字典获取对应的参数值」

**Comment by greyli** [comment]
已更新到勘误文件，谢谢！
