### ISSUE TITLE
疑似错将"HTML"写成"HTTP"

### ISSUE THREAD

**Issue by liuhao326** [greyli/helloflask#215]
第 2 章 Flask 与 HTTP => 2.3.2 响应格式 => 2. HTML => "因为HTML常常包含丰富的信息....因此，在普通的HTTP请求中我们使用***HTTP***作为响应的内容，这也是默认的数据类型。"

**Comment by greyli** [comment]
谢谢反馈，这一处已经在 1-2 版本修正了（各版本勘误见[这里](http://helloflask.com/book/errata/)）
