### ISSUE TITLE
.flaskenv不能被Flask检测到

### ISSUE THREAD

**Issue by nesteiner** [greyli/helloflask#219]
![2020-10-16 02-20-05 的屏幕截图](https://user-images.githubusercontent.com/46296608/96170426-25294d80-0f56-11eb-9824-63bd1c6c8166.png)

我太难了，还不容易解决重启的问题，又给我整出一个    
我是照着这个仓库的`.flaskenv`抄的，难道我有什么文件拉掉了？？  
ps: 我在这个文件夹里创建了虚拟目录，在这个目录里我都是用`env/bin/pip3`安装软件的

**Comment by nesteiner** [comment]
我从你的`sayhello`仓库拷贝过来
![2020-10-16 10-17-54 的屏幕截图](https://user-images.githubusercontent.com/46296608/96205450-2d56ac80-0f99-11eb-91b0-384ccd6bb459.png)
![2020-10-16 10-19-39 的屏幕截图](https://user-images.githubusercontent.com/46296608/96205454-2fb90680-0f99-11eb-9587-07e127a00b79.png)
  
我太难了

**Comment by greyli** [comment]
要不创建一个最小程序试试？先重新创建一个文件夹，重新创建一个虚拟环境，安装 flask 和 python-dotenv，然后创建一个最简单的 hello.py，再试试 .flaskenv 能不能正常读取。

**Comment by nesteiner** [comment]
![2020-10-16 11-29-43 的屏幕截图](https://user-images.githubusercontent.com/46296608/96209759-f38aa380-0fa2-11eb-86b8-f81f51c77252.png)

**Comment by greyli** [comment]
把 python-dotenv 全局安装试试，我之前在 Ubuntu 上遇到过激活虚拟环境但是仍然使用全局环境的 bug。另外执行 flask --help 有什么错误输出吗？

**Comment by nesteiner** [comment]
![2020-10-16 11-44-33 的屏幕截图](https://user-images.githubusercontent.com/46296608/96210688-fdada180-0fa4-11eb-9b3c-2110d69d5b18.png)
没有诶

**Comment by greyli** [comment]
全局安装 python-dotenv 和 flask 后执行 flask run 有用吗？可以换用系统自带的 Bash 试一下。

**Comment by nesteiner** [comment]
我更新了一下`sudo pip3 install python-dotenv flask --upgrade`  
终于好了，蟹蟹指点

**Comment by greyli** [comment]
虚拟环境下更新包之后 .flaskenv 也可以正常读取了吗？

**Comment by nesteiner** [comment]
嗯  
蟹蟹大佬

**Comment by greyli** [comment]
不客气 :)
