### ISSUE TITLE
Pipenv的python版本问题

### ISSUE THREAD

**Issue by BackMountainDevil** [greyli/helloflask#226]
# Env
win10 x64
python 3.9.0
flask 1.1.2
# 问题描述
在你的helloflask和sayhello仓库中的pipfile和.lock中，均没有指明python版本，然而我尝试了一下办法都没有创建出不知命python版本的pipfile，例如
```bash
pipenv inistall --three
pipenv inistall
```
无论是那个方法最后都会在文件里指明了py版本为我当前使用的python版本。我的本意是创建一个python版本是3.x的都可以的pipfile，但似乎没有这种选项，如果别人py版本和我py版本不一样的时候，要么装一样的，要么指定py路径使用他自己的py版本，但是这样每次都会有警告提示(虽然不影响)，只是好奇大佬怎么实现的。
```bash
Warning: Your Pipfile requires python_version 3.9, but you are using 3.7.3 (/home/k/.local/share/v/s/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
```

**Comment by greyli** [comment]
不想指定 Python 版本的话，手动删掉 `[requires]` 小节就可以了。

另，按照文档，使用 `$ pipenv --python 3` 命令可以指定为 Python 3.x 版本（或者你也可以手动编辑对应字段值）。

**Comment by BackMountainDevil** [comment]
十分感谢李老师的回答。手动删除ok哒
