### ISSUE TITLE
【勘误】WTForms自动对CSRF令牌字段进行验证

### ISSUE THREAD

**Issue by Skylor-Tang** [greyli/helloflask#227]
## Meta

- 版本：2019年11月第1版第5次
- 页码：p116
- 章节号或位置描述：开头的注意提示

## 错误详细信息
WTForm会自动对CSRF令牌字段进行验证，应该是Flask-WTF会自动对CSRF令牌字段进行验证

**Comment by greyli** [comment]
已添加到 [1-10 印次勘误](https://github.com/greyli/helloflask/blob/master/errata/errata1-10.md)，谢谢！
