### ISSUE TITLE
【勘误】backref()方法需要通过扩展类实例db进行调用

### ISSUE THREAD

**Issue by Skylor-Tang** [greyli/helloflask#228]
## Meta

- 版本：2019年11月第1版第5次
- 页码：p164
- 章节号或位置描述：最先出现的代码行

## 错误详细信息
关系属性的设置中，backref函数需要通过扩展类实例db进行调用，修改为
```python
class Singer(db.Model):
    ...
    songs = relationship('Song', backref=db.backref('singer', uselist=False))
```

**Comment by greyli** [comment]
已添加到 [1-10 印次勘误](https://github.com/greyli/helloflask/blob/master/errata/errata1-10.md)，谢谢！
