### ISSUE TITLE
【勘误】Heroku CLI login 添加参数

### ISSUE THREAD

**Issue by Yuxiaoy1** [greyli/helloflask#230]
## Meta

- 版本：2018年11月第1版第2次印刷
- 页码：P595
- 章节号或位置描述：14.6.1 通过 Heroku Git 部署

## 错误详细信息

依据 [Heroku CLI login now opens the browser by default](https://devcenter.heroku.com/changelog-items/1530)，使用 `heroku login` 登录 Heroku 时，默认会打开浏览器进行登入操作。若需使用 CLI 执行登入，需添加 `--interactive` 或简写形式 `-i`，即 `heroku login --interactive` 或 `heroku login -i`。

**Comment by greyli** [comment]
已添加到 [1-10 印次勘误](https://github.com/greyli/helloflask/blob/master/errata/errata1-10.md)，谢谢！
