### ISSUE TITLE
关于书182页构建邮件数据输入message后报错RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by yongquan-huang** [greyli/helloflask#232]
-操作系统为Windows，python版本3.7，Flask版本1.1.2
-邮件服务器配置代码跟书本一样，如下
![3](https://user-images.githubusercontent.com/52923165/111719372-b484b500-8896-11eb-9ead-22d4f74bd242.png)
-但是在python shell 输入message后报错
![4](https://user-images.githubusercontent.com/52923165/111719595-26f59500-8897-11eb-9f27-fe730aef2164.png)
-报错信息如下
raceback (most recent call last):
  File "<input>", line 3, in <module>
  File "E:\python37\lib\site-packages\flask_mail.py", line 273, in __init__
    sender = sender or current_app.extensions['mail'].default_sender
  File "E:\python37\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "E:\python37\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "E:\python37\lib\site-packages\flask\globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
--为什么工作在上下文之外呢？

**Comment by greyli** [comment]
截图不完整没法判断你执行的进入 Python Shell 的命令，不过书里给出的命令是 `flask shell`，而不是 `python`。具体区别见 P20。

**Comment by yongquan-huang** [comment]
> 整没法判断你执行的进入 Python Shell 的命令，不过书里给

谢谢大佬，报错解决了。不过我顺便有个问题想请教一下，使用flask shell进入的Python Shell 自动包含程序上下文。那如果没有使用flask shell的话，通过这种方式`os.getenv('SECRET_KEY', 'secret string'`时无法设置环境变量的吗？在windows只有通过set命令设置。

**Comment by greyli** [comment]
和书内容无关的其他问题请发到 [HelloFlask 论坛](https://discuss.helloflask.com)。
