### ISSUE TITLE
7.6 P215 关于 Flask-DebugToolbar 的描述笔误

### ISSUE THREAD

**Issue by greyli** [greyli/helloflask#243]
- 页数：P215

> 开发时不需要也不建议使用 Flask-DebugToolbar。

应为：

> 线上环境的程序不需要也不建议使用 Flask-DebugToolbar。

唉，鬼知道我为什么这样写。

**Comment by yuxiaoy1** [comment]
线上环境改为生产环境更为合适，flask-docs-zh 讨论区有过相关的投票。

**Comment by greyli** [comment]
已在 1-11 版本修正。
