### ISSUE TITLE
【勘误】行内验证器validate_字段属性名的参数问题

### ISSUE THREAD

**Issue by Skylor-Tang** [greyli/helloflask#244]
## Meta
+ 版本：2019年11月第1版第5次
+ 页码：p121
+ 章节号或位置描述：自定义验证器下的第一小节行内验证器

## 错误详细信息
在表单类中的自定义验证器需要的两个参数为form以及field，但是在表单类中定义的时候，form最好还是写成self（虽然没有影响），符合Python要求：
```python
class FortyTwoForm(FlaskForm):
    answer = IntegerField("The Number")
    submit = SubmitField()

    def validate_answer(self, field):  # form修改为self
        if field.data != 42:
            raise ValidationError('Must be 42.')
```

**Comment by greyli** [comment]
谢谢！这里为了便于理解验证器的通用编写模式，决定还是沿用 form，不过在下面的段落添加了解释，指出也可以按照惯例使用 self 命名类实例参数。
