### ISSUE TITLE
第3章 宏 p89页 下面一句话没看懂

### ISSUE THREAD

**Issue by BobcatsII** [greyli/helloflask#26]
“如果我们想在导入的宏中使用**第一个列表中的2、3、4项**，就需要...”
请问，这句话没有明白"第一个列表"是指哪个？
看了两遍没看明白o(╥﹏╥)o~

**Comment by greyli** [comment]
这段话上面有两个列表，第一个列表指的就是这段话上面两个列表中的第一个。是我的问题，这里本该使用数字标号的。

**Comment by BobcatsII** [comment]
哦，是指，"**这个foo.html的模板上下文中包含下列对象：**"这句下面的那个方框开头的列表吗？

**Comment by greyli** [comment]
是的

**Comment by BobcatsII** [comment]
好的，谢谢您~

**Comment by greyli** [comment]
不客气 :)
