### ISSUE TITLE
pipfile 在哪里？我怎么找不到

### ISSUE THREAD

**Issue by im-lh** [greyli/helloflask#262]
- 页数：

**Comment by greyli** [comment]
你指的是这个吗？

https://github.com/greyli/helloflask/blob/master/requirements/v1.txt

**Comment by im-lh** [comment]
> 你指的是这个吗？
> 
> https://github.com/greyli/helloflask/blob/master/requirements/v1.txt

也许是的，但书中并没有requirements 相关描述，而是以pipenv 进行依赖管理的示例，这会让人感到困惑。

**Comment by greyli** [comment]
不好意思，之前考虑不周。刚刚重新添加回来了 https://github.com/greyli/helloflask/blob/master/Pipfile

欢迎试用反馈。
