### ISSUE TITLE
1.2.2路由章节 

### ISSUE THREAD

**Issue by tiemkil** [greyli/helloflask#269]
1.2.2路由章节中，这段话“这个视图返回的响应会随着请求URL中的name变量而变化。假设程序运行在http://helloflask.com 上，当我们在浏览器里访问http://helloflask.com/hello/Grey 时，可以看到浏览器上显示“Hello，Grey！”。应为“greet/Grey”

**Comment by yuxiaoy1** [comment]
这个问题已经在 <https://docs.helloflask.com/book/1/errata/1-1/> 记录。
