### ISSUE TITLE
第2章 2.2.3 在Flask中处理请求 3 URL转换器 any的使用疑问

### ISSUE THREAD

**Issue by shuizaiku7** [greyli/helloflask#27]
我的理解any这里是用作枚举类型之用
实际运行以后，我发现这里any的取值只能是正则表达式解析为string的字母才行
（1）如果我想传入枚举类型的，数字表示的字符串有没有办法实现？
（2）如果我想传入枚举类型的，数字表示的字符串，通过类型转换解析为int类型有没有办法实现？

**Comment by greyli** [comment]
> 如果我想传入枚举类型的，数字表示的字符串有没有办法实现？

```py
@app.route("/number/<any('1', '2', '3'):num>")
def choose_a_number():
    ...
```

> 如果我想传入枚举类型的，数字表示的字符串，通过类型转换解析为int类型有没有办法实现？

这个我不太清楚，似乎没法直接使用转换器实现。
