### ISSUE TITLE
无法在python中直接使用escape

### ISSUE THREAD

**Issue by sumaut** [greyli/helloflask#276]
https://github.com/greyli/helloflask/blob/dfce5025033317dd42291907338e3a5accb71196/demos/http/app.py#L14C20-L14C20

ImportError: cannot import name 'escape' from 'jinja2'

**Comment by sumaut** [comment]
from markupsafe import escape

**Comment by hhhyyyqqq** [comment]
我也又同样问题，请问解决了吗

**Comment by greyli** [comment]
修改 escape 的导入语句即可，详见[示例](https://github.com/greyli/helloflask/pull/280/files#diff-0bee018e6bee18752bb758164497159de97d5eeab10e371f32bd82379b46d11dL14)。
