### ISSUE TITLE
使用pipenv环境运行第一个项目hello报错，使用conda环境程序正常运行，哪里还需要配置？

### ISSUE THREAD

**Issue by hhhyyyqqq** [greyli/helloflask#279]
对于helloflask的第一个项目hello，使用conda虚拟环境不报错，使用pipenv虚拟环境报错，具体配置和报错如下：

pipenv按照书中配置，使用项目提供的pipfile。
![Y~`RFQXZ7QB $@K`MG~IJ5B](https://github.com/greyli/helloflask/assets/74495722/8adff7d0-9168-47fc-88ba-be7d36c41a79)

报错：
![9R6RPKSP5HES)KM PUABOEQ](https://github.com/greyli/helloflask/assets/74495722/4a106862-49e0-40af-a58a-9c7c4e2d042e)

这个错误是我哪里没有配置好吗

conda是自己配的环境，运行没有问题。
![(AJY4U4}AX%W}0IL ~9T$QH](https://github.com/greyli/helloflask/assets/74495722/9b0eb633-ca50-4e46-a8f6-9aa98d57b72d)

**Comment by yuxiaoy1** [comment]
目前已不推荐使用pipenv管理虚拟环境，可以尝试其他工具(venv/pdm/poetry...)

**Comment by greyli** [comment]
用 PyCharm 试了下也没问题。在 Application 那里填写 app 实例的名称，虚拟环境变量不需要设置：

<img width="933" alt="image" src="https://github.com/greyli/helloflask/assets/12967000/9004b571-6b82-40ba-a1f8-32ab4b0c2250">

另外如果继续报错，那大概是你的解释器选择的并不是 Pipenv 创建的那个。可以用 `pipenv --venv` 命令来查看对应的虚拟环境目录，然后使用右下角的按钮添加对应的解释器（找到 Scipts/python.exe 或是 bin/python）：

<img width="566" alt="image" src="https://github.com/greyli/helloflask/assets/12967000/0c3c5f2c-6347-4719-b9c3-a06a127c40f8">
