### ISSUE TITLE
第5章代码清单5-11后面在flask shell中的一段代码

### ISSUE THREAD

**Issue by zerosail** [greyli/helloflask#28]
```
king = Writer(name='Stephen King')
carrie = Book(name='Carrie')
it = Book(name='IT')
db.session.add(king)
db.session.add(carrie)
db.session.add(it)
db.session.commit()

carrie.writer = king
carrie.writer
king.books
it.writer = writer
king.books
```

这里的 it.writer = writer
应该是 it.writer = king 吧？
然后两行king.books都报错
AttributeError: 'Book' object has no attribute 'name'

**Comment by greyli** [comment]
@zerosail 感谢反馈！这里第2行和第3行的name应为title，属于笔误，详情见勘误文件。

**Comment by zerosail** [comment]
> @zerosail 感谢反馈！这里第2行和第3行的name应为title，属于笔误，详情见勘误文件。
回复真是神速~~
笔误这边我已经知道了
实际在敲shell代码的时候已经修改为title了
不过上面复制的代码忘了改过来

问题就是报错
AttributeError: 'Book' object has no attribute 'name'

**Comment by zerosail** [comment]
![tim 20180926150405](https://user-images.githubusercontent.com/34032543/46062794-7e6e8a80-c19d-11e8-8e5f-1303201846ad.png)
实际情况就是这样
我修改过
`return '<Book %r>' % self.name`
为
`return '<Book %r>' % self.title`
但依然提示
AttributeError: 'Book' object has no attribute 'name'

**Comment by zerosail** [comment]
解决问题了，
`return '<Book %r>' % self.name`
修改为
`return '<Book %r>' % self.title`
然后退出flask shell再重新进
重新敲一遍之前的那些代码就可以了

**Comment by greyli** [comment]
我考虑了一下，当时应该是想把Book类里的那个属性命名为name，这样勘误只需要更新类定义中的那一处即可，即https://github.com/greyli/helloflask/blob/master/demos/database/app.py#L230。

**Comment by greyli** [comment]
勘误和源码已更新，Book类中的title属性名改为name。
