### ISSUE TITLE
第五章代码清单5-14后面的shell里的代码，笔误，少了个=号

### ISSUE THREAD

**Issue by zerosail** [greyli/helloflask#29]
`tokyo = Capital(name'Tokyo')`
应该是
`tokyo = Capital(name='Tokyo')`

我买的多看阅读的电子书
不确定实体书有没有这个错误

**Comment by greyli** [comment]
感谢反馈！这个是笔误，稍后会添加到勘误表中。

**Comment by greyli** [comment]
勘误已更新。
