### ISSUE TITLE
第一部分 第四章 表单  110页  login.html 和 basic.html

### ISSUE THREAD

**Issue by BobcatsII** [greyli/helloflask#31]
今天回顾复习"表单"的时候偶然发现
代码清单4-2里面"**return render_template('login.html', form=form)**"
和代码清单4-3的标题"**form/templates/basic.html**"
一开始看的时候没注意到这个问题，
请问，这里应该都是basic.html的模板吧？
还请指点。

**Comment by greyli** [comment]
是的，这里应该是basic.html，稍后会加到勘误里。感谢反馈！

**Comment by greyli** [comment]
勘误文件已更新，谢谢。
