### ISSUE TITLE
书籍代码勘误

### ISSUE THREAD

**Issue by VladCraste** [greyli/helloflask#32]
你好作者，我刚买了你的书发现第二章36页，URL变量转换器代码的修饰器

@app.route('goback/<int:year>')
def go_back(year):
    return '<p>Welcome to %d!<!p>' % (2018-year)

应该在里面加一个 / 
@app.route('/goback/<int:year>')

**Comment by greyli** [comment]
是的，这里漏掉了。稍后会加到勘误里，感谢反馈~

**Comment by greyli** [comment]
勘误文件已更新，谢谢。
