### ISSUE TITLE
5.3.3 的建议

### ISSUE THREAD

**Issue by jiangyanglinlan** [greyli/helloflask#38]
*5.3.3 创建数据库和表这一章(145 页),*

第一个`注意`下面, 通过下面的方式可以查看模型对应的 SQL 模式(建表语句)
```python
>>> from sqlalchemy.schema import CreateTable
>>> print(CreateTable(Note.__table__))

CREATE TABLE note (
        id INTEGER NOT NULL,
        body TEXT,
        PRIMARY KEY (id)
)
```

此处应该先 `from app import Note`,  , 否则会得到 `NameError: name 'Note' is not defined`, 但是书中上下文并没有提到这个。对于 Python 初学者可能不太友好。

### 环境

* Python版本：3.6.1
* Flask版本：1.0.2
* 操作系统：windows 10

**Comment by greyli** [comment]
好的，谢谢，稍后会更新到相关文件里。

**Comment by greyli** [comment]
已更新勘误，谢谢。
