### ISSUE TITLE
pycharm不能运行flask

### ISSUE THREAD

**Issue by RYLF** [greyli/helloflask#4]
问题：按照下图设置pycharm，不能正确运行flask    (python2.7.13，pycharm版本5.0.3)

![](http://i2.bvimg.com/659841/4edc683030aa92f7.png)

**Comment by greyli** [comment]
这个是因为PyCharm版本太低，不支持通过模块来执行命令。新版本的PyCharm在第一个箭头位置有一个下拉选项，可以选择Module，而不是Script。通过添加-m选项可以起到类似的效果，即`python -m flask run`。感谢你的反馈，我会把这个问题放到FAQ中。
