### ISSUE TITLE
笔者是不是忘了打tag了

### ISSUE THREAD

**Issue by NiceBlueChai** [greyli/helloflask#40]
clone仓库之后用git tag命令看不到任何标签,

**Comment by greyli** [comment]
helloflask项目没有设置标签，设置标签的是第2部分的5个项目。前言里这部分内容安排不够合理，应该添加一个提示的。这个问题我已经记录在[这里](https://github.com/greyli/helloflask/blob/master/improvement/improvement.md#%E4%BB%8B%E7%BB%8Dgit%E6%A0%87%E7%AD%BE%E9%83%A8%E5%88%86%E5%AE%B9%E6%98%93%E4%BA%A7%E7%94%9F%E8%AF%AF%E8%A7%A3)了。抱歉给你带来不便 :)
