### ISSUE TITLE
url_for模板中的参数问题

### ISSUE THREAD

**Issue by byis** [greyli/helloflask#41]
感谢作者详细的讲解 大部分内容都很棒
可能是因为时间紧迫 有些地方存在容易让人疑惑
8.3.1分页显示文章列表
为了便于重用，我们可以创建一个pager()宏：
```
{% macro pager(pagination, fragment='') %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#'}}">
      <span aria-hidden="true">&larr;</span> Newer
      </a>
    </li>
    <li class="page-item class="next {% if not pagination.has_next %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#'}}">
      Older <span aria-hidden="true">&rarr;</span>
      </a>
    </li>
  </ul>
</nav>
{% endmacro %}
```

请问在宏内部调用url_for() 为什么传入的参数里有**kwargs
这是形参不定长参数 为什么会写在传入的实参中？

**Comment by byis** [comment]
"""
为了便于重用，我们可以创建一个pager()宏：
{% macro pager(pagination, fragment='') %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#'}}">
      <span aria-hidden="true">&larr;</span> Newer
      </a>
    </li>
    <li class="page-item class="next {% if not pagination.has_next %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#'}}">
      Older <span aria-hidden="true">&rarr;</span>
      </a>
    </li>
  </ul>
</nav>
{% endmacro %}

"""

**Comment by byis** [comment]
```
为了便于重用，我们可以创建一个pager()宏：
{% macro pager(pagination, fragment='') %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#'}}">
      <span aria-hidden="true">&larr;</span> Newer
      </a>
    </li>
    <li class="page-item class="next {% if not pagination.has_next %}disabled{% endif %}">
      <a class="page-link" href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#'}}">
      Older <span aria-hidden="true">&rarr;</span>
      </a>
    </li>
  </ul>
</nav>
{% endmacro %}
```

**Comment by greyli** [comment]
这里的意思是把传入宏的关键字参数传递给 `url_for()` 函数。

**Comment by byis** [comment]
> 这里的目的是把传入宏的关键字参数传递给 `url_for()` 函数。

是让url_for()替宏去接收不定长参数吗?

**Comment by greyli** [comment]
宏默认会自定接受额外的关键字参数，在宏内部你可以直接使用 `kwargs` 字典来获取这些额外的关键字参数。这里直接把这个字典传入 `url_for()` 函数。

顺便说一下，Jinja 宏传入关键字参数的实现有一点不太符合直觉。在定义宏的时候，并不需要传入 `**kwargs`。在宏的内部，你可以直接通过 `kwargs` 字典来获取所有传入的关键字参数。

也就是说，是 `Jinja` 自动处理这些传入的关键字参数的。另一个宏内部可以直接使用的变量是 `varargs`，这个元组存储所有传入的额外位置参数，即 `*args`。

如果明天有时间，我会写一篇文章总结一下这部分内容，书里面没有提及。

**Comment by byis** [comment]
> 宏默认会自定接受额外的关键字参数，在宏内部你可以直接使用 `kwargs` 字典来获取这些额外的关键字参数。这里直接把这个字典传入 `url_for()` 函数。
> 
> 顺便说一下，Jinja 宏传入关键字参数的实现有一点不太符合直觉。在定义宏的时候，并不需要传入 `**kwargs`。在宏的内部，你可以直接通过 `kwargs` 字典来获取所有传入的关键字参数。
> 
> 也就是说，是 `Jinja` 自动处理这些传入的关键字参数的。另一个宏内部可以直接使用的变量是 `varargs`，这个元组存储所有传入的额外位置参数，即 `*args`。
> 
> 如果明天有时间，我会写一篇文章总结一下这部分内容，书里面没有提及。

谢谢 现在很清楚了 这个代码确实比较让人惊讶 就像第一次见到这个
```python
def formater(text):
    ...
        return lambda *a, **kw: text % kw

```

**Comment by greyli** [comment]
PS:  [如何向Jinja宏传递额外参数？](https://zhuanlan.zhihu.com/p/47350126)
