### ISSUE TITLE
windows pycharm运行一直报错

### ISSUE THREAD

**Issue by zshg8** [greyli/helloflask#43]
报错信息如下：
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
1）set FLASK_APP=app.py也解决不了问题
2）app.py在demo/hello文件件下面
3）貌似将app.py目录挪到项目根目录下面就没有报错。
麻烦看一下谢谢！

**Comment by greyli** [comment]
如果你的程序（app.py）在 demo/hello 目录下，那就需要先切换到这个目录，然后再执行 flask run 。

**Comment by zshg8** [comment]
您好，就是切换到hello目录下面执行的，还是报错。

**Comment by zshg8** [comment]
可以了，现在通过Pycharm里面的terminal 中输入
flask run --host=0.0.0.0没有报错了
但是直接通过菜单运行按钮还是不错，不知道咋回事。有可能是不是我的Pycharm版本问题（2017版）

**Comment by greyli** [comment]
通过菜单运行按钮运行报什么错？配置正确吗？

**Comment by zshg8** [comment]
还是报这个：
  Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
进程完成，退出码 2

配置如下：
脚本：C:\Users\zsg\.virtualenvs\helloflask-NZqksH29\Scripts\flask.exe
参数：run --host=0.0.0.0

**Comment by greyli** [comment]
看样子是启动配置的问题，方便的话，可以截图给我看一下。

**Comment by greyli** [comment]
@zshg8 working directory那里指的是工作目录，应该设置成你的app.py文件所在的项目根目录。

**Comment by zshg8** [comment]
@greyli 谢谢，我试了设置成项目根目录还是报错，要设置成项目根目录下面的app.py所在的目录就可以了。

**Comment by greyli** [comment]
不客气，这里的工作目录必须是app.py所在的目录，或是程序包所在的目录。手动执行flask run命令时也是这样。
