### ISSUE TITLE
5.62结迁移数据库

### ISSUE THREAD

**Issue by gweid** [greyli/helloflask#44]
### 期望的行为

生成迁移环境和更新数据库按照书中代码没有效果

```python
在这里给出相关代码。
```

### 实际情况

“”“生成迁移脚本”“”
flask db revison -m "create note timestamp"
“”“更新数据库”“”
flask db upgrade head
不知道这样对不对

### 环境

* Python版本：3.63
* Flask版本：1.02
* 操作系统：window

**Comment by greyli** [comment]
书里的命令不是这样的吧？

**Comment by greyli** [comment]
建议你再按照书里的命令依次试一下。flask db revison 只是用来生成空白迁移脚本的。
