### ISSUE TITLE
邮件

### ISSUE THREAD

**Issue by goodbad3** [greyli/helloflask#46]
状态 | 信息 | 收到最后一次活动 | 打开 | 点击
-- | -- | -- | -- | --
处理 | 致：573908896@qq.com 你好，世界！ | 2018/10/10上午9:03 UTC + 00:00 | 0 | 0

sendgrid 不给发邮件？？？？？

**Comment by goodbad3** [comment]
reply: b'235 Authentication successful\r\n'
reply: retcode (235); Msg: b'Authentication successful'
send: 'mail FROM:<apikey> size=349\r\n'
reply: b'250 Sender address accepted\r\n'
reply: retcode (250); Msg: b'Sender address accepted'
send: 'rcpt TO:<573908896@qq.com>\r\n'
reply: b'250 Recipient address accepted\r\n'
reply: retcode (250); Msg: b'Recipient address accepted'
send: 'data\r\n'
reply: b'354 Continue\r\n'
reply: retcode (354); Msg: b'Continue'
data: (354, b'Continue')
send: b'Content-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: 7bit\r\nSubject: Hello, World!\r\nFrom: =?utf-8?q?Grey_Li?= <apikey>\r\nTo: 573908896@qq.com\r\nDate: Wed, 10 Oct 2018 17:03:43 +0800\r\nMessage-ID: <153916222073.19728.2943808533689197805@LAPTOP-T3MKOGPE>\r\n\r\nAcross the Great Wall we can reach every corner in the world.\r\n.\r\n'
reply: b'250 Ok: queued as mJrrqGkuRSin9CiHao-5pA\r\n'
reply: retcode (250); Msg: b'Ok: queued as mJrrqGkuRSin9CiHao-5pA'
data: (250, b'Ok: queued as mJrrqGkuRSin9CiHao-5pA')
send: 'quit\r\n'
reply: b'221 See you later\r\n'

**Comment by goodbad3** [comment]
qq收不到

**Comment by goodbad3** [comment]
由于以下原因导致电子邮件被延期：[IP受收件人服务器限制]

回复于2018/10/10 UTC时间上午9:23 + 00:00

由于以下原因导致电子邮件被延期：[IP受收件人服务器限制]

回复于2018/10/10 UTC时间上午9:22 + 00:00

由于以下原因导致电子邮件被延期：[IP受收件人服务器限制]

回复于2018/10/10 UTC时间上午9:22 + 00:00

由于以下原因导致电子邮件被延期：[IP受收件人服务器限制]

隐藏最新响应

**Comment by cslanjian** [comment]
我其他邮箱测试正常，可以收到

**Comment by greyli** [comment]
好的，先关闭了。
