### ISSUE TITLE
勘误总结中的问题

### ISSUE THREAD

**Issue by jzoy** [greyli/helloflask#47]
勘误总结中 https://github.com/greyli/helloflask/blob/master/errata/errata.md

5.5.2.4 | P163 | 第3个代码块第6行 | it.writer = writer | it.writer = king
-- | -- | -- | -- | --

这行代码应该不是第三个代码块，是不是应该界定成第二个代码块，会比较准确？

**Comment by jzoy** [comment]
5.7.1.2 | P174 | 最后1个代码块第1行 | Post.quer2y.get(2) | Post.query.get(2)
-- | -- | -- | -- | --


这个是第四个代码块中的内容

**Comment by jzoy** [comment]
理解错了。。。你是按照章节的代码块来数的，我理解成页码上的顺序了。。。

**Comment by greyli** [comment]
因为电子书页码不固定，所以这里的定位逻辑是为了兼顾电子书的。有时间我会在勘误里添加一个说明。

**Comment by jzoy** [comment]
非常感谢，在看你写的书，以前教程都看翻译的，发现你写的书完全不输国外的书籍，还更适合中国人阅读，感谢感谢！@！

**Comment by greyli** [comment]
感谢认可 :)
