### ISSUE TITLE
设置环境变量后报错

### ISSUE THREAD

**Issue by RYLF** [greyli/helloflask#5]
环境：python2.7 

过程：新建.flaskenv文件，写入环境变量FLASK_ENV=development，运行flask run

结果：TypeError: environment can only contain strings

**Comment by greyli** [comment]
@RYLF 这个是werkzeug的一个bug，这个月底会发布新版本修复这个问题。我现在在外面，回去发一下临时的解决办法，然后处理其他两个issue。感谢你的反馈！

**Comment by greyli** [comment]
对于这个问题，我待会在[专栏](https://zhuanlan.zhihu.com/flask)写一篇文章介绍几个常用的临时解决方法。感谢反馈，我先关闭了。

**Comment by opaser** [comment]
请问处理方案在哪里

**Comment by greyli** [comment]
临时可以通过修改 python-dotenv 源码解决，找到图示文件这一行并修改：
![image](https://user-images.githubusercontent.com/12967000/49295954-fafd4c80-f4f1-11e8-828f-7570cf5e4995.png)

**Comment by opaser** [comment]
谢谢 已解决

**Comment by greyli** [comment]
python-dotenv 发布新版本了，使用下面的命令更新即可解决这个问题，不必再修改源码：
```
$ pip install -U python-dotenv
```

**Comment by opaser** [comment]
关于3.4.1 空白控制中我去除 - 并且将 
app.jinja_env.trim_blocks = True
app.jinja_env.lstrip_blocks = True
去掉 
和未修改前 页面并没有什么差别 这是为什么
