### ISSUE TITLE
纸质书51页图2-11笔误

### ISSUE THREAD

**Issue by Abyssknight** [greyli/helloflask#50]
* 章节位置（比如3.3.2）：2.3.3
* 页数（如果是纸书的话）：48页 图 2-11 Cookie 设置示意图
* 错误文字：200 OK
* 正确文字：302 Found
* 备注：服务器重定向响应

**Comment by greyli** [comment]
我想这里并没有发生重定向。

**Comment by Abyssknight** [comment]
好的，感谢!

**Comment by greyli** [comment]
不客气
