### ISSUE TITLE
第5章  第153页 5-5代码 请教

### ISSUE THREAD

**Issue by BobcatsII** [greyli/helloflask#52]
```
@app.route('/')
def index():
    form = DeleteForm()
    notes = Note.query.all()
    return render_template('index.html', notes=notes, form=form)
```
请教一下，这段代码中的 `form = DeleteForm()` 这一行将DeleteForm()这个类实例化为form，没有看明白，渲染index.html模板的时候是没用到吧？

**Comment by greyli** [comment]
渲染模板的时候传入了这个`form`实例，模板下列位置调用了它：https://github.com/greyli/helloflask/blob/master/demos/database/templates/index.html#L13-L14

**Comment by BobcatsII** [comment]
哦，晓得了，感谢。

**Comment by BobcatsII** [comment]
我只局限在"2.Read"这块书本上的代码片段了，只想到了既然是Read，为啥放了个"DeleteForm()"，后面"4.Delete"的章节还没有看到那边，误以为写错了。
