### ISSUE TITLE
纸书3.2.5第87页通过模板环境对象添加全局属性有疑问

### ISSUE THREAD

**Issue by waynerv** [greyli/helloflask#54]
* 章节位置（比如3.3.2）：3.2.5 在87页第1个注意下面的第一段文字，倒数第二句部分
* 页数（如果是纸书的话）：87
* 错误文字：：这通过向对应的字典属性中添加一个键值对实现，**传入模板的名称作为键**，对应的函数对象或变量作为值。
* 正确文字：这通过向对应的字典属性中添加一个键值对实现，**传入函数对象或变量的名称作为键**，对应的函数对象或变量作为值。
* 备注：查阅官方文档后发现这里的键就是值名称的字符串表示，表述为‘’用模板的名称‘’容易引起读者歧义和不解。官方文档实例代码如下：
`def reverse_filter(s):
    return s[::-1]
app.jinja_env.filters['reverse'] = reverse_filter`

**Comment by greyli** [comment]
或许可以把隐藏的那个动词补充一下，改为“**使用**传入模板的名称作为键”。
