### ISSUE TITLE
第5章  5.5.2 P160  3.建立关系  代码问题

### ISSUE THREAD

**Issue by BobcatsII** [greyli/helloflask#58]
* 章节位置：5.5.2
* 页数（纸书）：160页
* 错误文字：
>>> spam.author_id = 1
>>> db.session.commit()

* 正确文字：
>>> spam.author_id = 1
>>> ham.author_id = 1
>>> db.session.commit()

* 备注：
因为下面返回的Article对象列表为：
foo.articles
[<Article 'Spam'>, <Article 'Ham'>]
2个对象，
所以应该是漏了 ">>> ham.author_id = 1" 这个外键，
否则只会返回 "[<Article 'Spam'>]" 1个对象

(或者反过来改动，只返回
foo.articles
[<Article 'Spam'>]
这一个对象)

**Comment by greyli** [comment]
已更新勘误，谢谢。
