### ISSUE TITLE
勘误P247代码8-19

### ISSUE THREAD

**Issue by hallucigenia** [greyli/helloflask#62]
* 章节位置（比如3.3.2）：8.2.3
* 页数（如果是纸书的话）：P247
* 错误文字：from **wtforms** import DataRequired
* 正确文字：from **wrforms.validators** import DataRequired
* 备注：代码8-19 line 2

**Comment by hallucigenia** [comment]
章节位置（比如3.3.2）：8.3.5
页数（如果是纸书的话）：P264
错误文字：(%Y-%m-%dT%H:%M:%SZ') 
正确文字：(**'**%Y-%m-%dT%H:%M:%SZ') 
备注：代码第12行

**Comment by hallucigenia** [comment]
章节位置（比如3.3.2）：8.6
页数（如果是纸书的话）：P282
错误文字：('400.html', description=e.description)
正确文字：('errors/400.html', description=e.description)
备注：代码清单8-38 line 4

**Comment by greyli** [comment]
@hallucigenia 谢谢，下周会统一更新到勘误。

**Comment by greyli** [comment]
感谢反馈，已更新到勘误。
