### ISSUE TITLE
第9章  9.3.3  315页  整页最后一行

### ISSUE THREAD

**Issue by BobcatsII** [greyli/helloflask#77]
* 章节位置：第9章  9.3.3
* 页数（纸书）：315页
* 错误文字：整页最下面一行代码“auth.resend_confirmation”
* 正确文字：auth.resend_confirm_email
* 备注：代码中没有找到"auth.resend_confirmation"这段，联系flash的message变量里面的url_for的参数是auth.resend_confirm_email，貌似应该是印错了，还请核对，谢谢。

**Comment by greyli** [comment]
感谢反馈。实例程序经过了大量重构和改写，但是书里对应的部分有些忘记更新，实在抱歉。明天会更新到勘误。

**Comment by BobcatsII** [comment]
好的，ヽ(￣▽￣)و，谢谢~

**Comment by greyli** [comment]
已更新勘误，谢谢！
