### ISSUE TITLE
纸质版第一版第一次印刷P37文字错误

### ISSUE THREAD

**Issue by Merpyzf** [greyli/helloflask#79]
倒数第八行中 "在玩具程序中……"，应该是应用程序吧？

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by greyli** [comment]
你好，这里的确是指玩具程序。在实际程序里，我们通常会把这些初始化操作使用自定义命令或是手动操作来实现。

**Comment by Merpyzf** [comment]
学习了！
