### ISSUE TITLE
3.1.1　创建模板 里的笔误?

### ISSUE THREAD

**Issue by python012** [greyli/helloflask#8]
其中有一小节提示

> 这里创建了一个基础的HTML文档结构，关于HTML5的结构组成，你可以访问https://www.w3.org/wiki/HTML_structural_elements 了解。

其中**HTML5**里的**5**是多余的吗？感觉有点突兀，而且后面给的链接也是普通版本HTML结构的介绍。

**Comment by greyli** [comment]
这里的确有些多余，感谢反馈！后期会更新这个链接，然后去掉这个数字。

顺便说一句，这里的链接现在被重定向到了MDN，原链接指向的内容可以参考[archive.org的备份](https://web.archive.org/web/20160429055913/http://www.w3.org/wiki/HTML_structural_elements)。原链接重点介绍了一些HTML5的新元素，虽然MDN文档也介绍了这些内容，但是没有明确HTML版本。
