### ISSUE TITLE
1.7 节 URL与端点示例的错误

### ISSUE THREAD

**Issue by realzhangm** [greyli/helloflask#83]
* 章节位置：1.7
* 页数（如果是纸书的话）：23
* 错误文字：这是使用 url_for('**say_hello**', name = 'jack')得到的URL为 “/hello/jack"
* 正确文字：这是使用 url_for('**greet**', name = 'jack')得到的URL为 “/hello/jack"
* 备注：不符逻辑

**Comment by greyli** [comment]
感谢反馈，已包含再勘误中。
