### ISSUE TITLE
第七章，代码清单7-7，index.html 第二行

### ISSUE THREAD

**Issue by realzhangm** [greyli/helloflask#85]
* 章节位置（比如3.3.2）： 7.2.3
* 页数（如果是纸书的话）：205
* 错误文字：{% from 'macros.html' import render_form %}
* 正确文字：{% from 'bootstrap/form.html' import render_form %}
* 备注：

**Comment by greyli** [comment]
你好，感谢反馈。我看了一下，这里还没有介绍 Bootstrap-Flask，所以使用的是前面介绍的 form_field 宏来渲染表单字段的。

**Comment by meizhaohui** [comment]
{% from 'macros.html' import render_form %} 此处的宏可参考纸质书P120页代码清单4-9内容，7.3.2节快速渲染表单中使用Bootstrap-Flask优化了此处代码。

**Comment by greyli** [comment]
先关闭了，感谢反馈。后续有疑问可以添加评论或是重新打开。
