### ISSUE TITLE
P186 没有在Shell中 import os

### ISSUE THREAD

**Issue by LeeHangTung** [greyli/helloflask#88]
示例中用到了os库，但是没有import os语句。

**Comment by greyli** [comment]
出于篇幅的考虑，书里面大部分代码块并没有写出完整的导入语句，只在第一次出现陌生模块的时候给出导入语句。这里加上会更友好，周末会统一更新，谢谢。

**Comment by greyli** [comment]
已添加到「可改进实现」，谢谢。
