### ISSUE TITLE
请教：关于SelectField的选项在存入数据库时的问题

### ISSUE THREAD

**Issue by BobcatsII** [greyli/helloflask#95]
描述：
今天在Form中（forms/deploy.py）使用SelectField定义下拉菜单选项，定义的choices=[(1, '192.168.250.141'), (2, '172.18.1.152')]，在视图函数(buleprints/deploy.py)中 POST 添加到数据库的数据只有choices列表里元组的第一个元素，即1或2，请问如何才能获取到第二个元素？
_______________________________________
我的尝试：
我尝试过去掉 coerce=int ，使 choices=[('192.168.250.141', '192.168.250.141'), ('172.18.1.152', '172.18.1.152')] 变成这样的写法，虽然可以让存入数据库的数据变成和下拉菜单选择的一样，但是，还是想知道choices=[(1, '192.168.250.141'), (2, '172.18.1.152')]这种形式的是否能通过某种配置，达到同样的效果。
________________________________________
代码：
forms/deploy.py
```py
class CreateDeployForm(FlaskForm):
    hosts = [(1, '192.168.250.141'), (2, '172.18.1.152')]
    deploy_project = SelectField(label='项目名称', validators=[DataRequired()], choices=[] ,coerce=int)
    deploy_ip = SelectField(label='IP地址', validators=[DataRequired()], choices=hosts, coerce=int)
    deploy_version = SelectField(label='选择版本', validators=[DataRequired()], choices=[], coerce=int)
    deploy_user = SelectField(label='选择用户', validators=[DataRequired()], choices=[], coerce=int)
    submit = SubmitField('确认部署')

    def __init__(self, *args, **kwargs):
        super(CreateDeployForm, self).__init__(*args, **kwargs)
        self.deploy_project.choices = [(deploy_name.id, deploy_name.project_name) for deploy_name in Project.query.order_by(Project.project_name).all()]
        self.deploy_version.choices = [(deploy_ver.id, deploy_ver.deploy_version) for deploy_ver in Version.query.order_by(Version.deploy_version).all()]
        self.deploy_user.choices = [(deploy_user.id, deploy_user.username) for deploy_user in User.query.order_by(User.username).all()]
```
________________________________________________________________________________
buleprints/deploy.py
```py
@deploy_bp.route('/create', methods=['GET', 'POST'])
def create():
    form = CreateDeployForm()
    if form.validate_on_submit():
        user = form.deploy_user.data
        project = form.deploy_project.data
        ip = form.deploy_ip.data
        version = form.deploy_version.data
        deploy = DeployLog(dply_user=user, dply_item=project, dply_ip=ip, dply_version=version, dply_stat='1')
        db.session.add(deploy)
        if not project or not ip or not version:
            flash('缺少参数,请确认参数','warning')
        else:
            db.session.commit()
            flash('部署信息已提交', 'success')
            return redirect(url_for('.index'))
    return render_template('deploy/create_deploy.html', form=form)
```
——————————————————————————————————
传入参数：
项目名称 
www
IP地址 
192.168.250.141
选择版本 
1.2.1
选择用户
linan 
__________________________________________________________________________________
数据现象：
1	1	1	1	2018-11-23 10:46:46	1
1	1	1	1	2018-11-23 10:46:49	1
1	1	2	1	2018-11-23 10:47:02	1
__________________________________________________________________________________

代码的github站点：
https://github.com/BobcatsII/Opps.git

问题页面：
http://127.0.0.1:5000/deploy

——————————————————————————————————
麻烦您抽时间指导一下， 感谢！！

**Comment by greyli** [comment]
不好意思，最近比较忙。看到你这个数据是从数据库里读取出来的，那么获取到 id 的值后（就是你表单的那个 1 和 2），可以再重新从数据库里读取对应的值。
